### ISSUE TITLE
max should be calc?

### ISSUE THREAD

**Issue by donaldguy** [csstools/custom-units#1]
or `calc(max( .. ))` ? 

or some actual rounding?

or is there another plugin I am missing that would make max sufficient/desirable?

**Comment by DanielRios549** [comment]
It probably should be a `calc()`, since it multiplies the value you pass by the value of the custom property, it does not compare two values to decide what is higher, despite the fact `max()` function appears to be working exactly as the `calc()` when only one value is passed

**Comment by romainmenke** [comment]
I don't think there is any difference in output between `max()` or `calc()`.
`max()` is one char shorter, so think of this as minification 🎉 

-----

If there is an actual bug, please let me know and I will re-open this issue.
